# Generated by Django 3.1 on 2023-11-07 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='数据编号')),
                ('dataUrl', models.CharField(max_length=500, verbose_name='数据路径')),
                ('upload_time', models.DateTimeField(auto_now_add=True)),
                ('dataname', models.CharField(max_length=150)),
            ],
            options={
                'verbose_name': '数据信息表',
                'db_table': 'Datainfo',
            },
        ),
    ]
