# Generated by Django 4.2.6 on 2023-11-06 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('picprocess', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='data',
            options={'verbose_name': '数据信息表'},
        ),
        migrations.AlterModelTable(
            name='data',
            table='Datainfo',
        ),
    ]
